name: Reusable docker workflow

description: Reusable docker workflow.

inputs:
  tag:
    description: "A tag to use for the image"
    default: "no_model"

outputs:
  tags:
    description: "tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    # We require additional space due to the large size of our image. (~10GB)
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Docker meta:${{ inputs.tag }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/whisperx
        tags: |
          ${{ inputs.tag }}
          type=sha,prefix=${{ inputs.tag }}-
          type=raw,value=latest,enable=${{ inputs.tag == 'no_model' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # You may need to manage write and read access of GitHub Actions for repositories in the container settings.
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
